import { createContext, useContext, useState, type ReactNode } from 'react'

export type Language = 'es' | 'pl' | 'en' | 'cs' | 'sk'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.privacy': 'Privacidad',
    'nav.start': 'Comenzar',

    // Hero
    'hero.badge': 'Agricultura del Futuro',
    'hero.title1': 'Transforma tu',
    'hero.title2': 'Agricultura con Drones',
    'hero.description': 'Servicios de precisión agrícola con tecnología de vanguardia. Maximiza el rendimiento de tus cultivos con soluciones inteligentes.',
    'hero.cta': 'Solicitar Servicio',
    'hero.viewServices': 'Ver Servicios',

    // Stats
    'stats.hectares': 'Hectáreas Tratadas',
    'stats.precision': 'Precisión',
    'stats.response': 'Respuesta',
    'stats.clients': 'Clientes',

    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones',
    'services.subtitleHighlight': 'Agrícolas',
    'service.fumigation.title': 'Fumigación con Drones',
    'service.fumigation.desc': 'Aplicación precisa de tratamientos fitosanitarios con tecnología de última generación.',
    'service.painting.title': 'Pintura de Invernaderos',
    'service.painting.desc': 'Protección UV y control climático para optimizar el crecimiento de tus cultivos.',
    'service.mapping.title': 'Mapeo Aéreo',
    'service.mapping.desc': 'Análisis detallado de terrenos con imágenes de alta resolución y datos precisos.',
    'service.elevation.title': 'Modelos de Elevación',
    'service.elevation.desc': 'Planificación de riego y drenaje con modelos topográficos 3D de alta precisión.',
    'service.rental.title': 'Alquiler de Drones',
    'service.rental.desc': 'Alquiler de drones agrícolas profesionales con o sin operador para tus proyectos.',

    // About
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Innovación al servicio del',
    'about.subtitleHighlight': 'campo',
    'about.description': 'Somos pioneros en la aplicación de tecnología de drones para la agricultura. Nuestro equipo de expertos combina conocimiento agrícola con tecnología de vanguardia para ofrecer soluciones que transforman la productividad de tu campo.',
    'about.feature1': 'Tecnología de última generación',
    'about.feature2': 'Equipo de expertos certificados',
    'about.feature3': 'Compromiso con el medio ambiente',
    'about.feature4': 'Resultados garantizados',
    'about.years': 'Años de Experiencia',
    'about.drones': 'Drones en Flota',
    'about.support': 'Soporte Técnico',
    'about.satisfaction': 'Satisfacción',

    // CTA
    'cta.title': '¿Listo para',
    'cta.titleHighlight': 'transformar',
    'cta.titleEnd': 'tu agricultura?',
    'cta.description': 'Únete a cientos de agricultores que ya están aprovechando el poder de los drones. Solicita tu primera consulta gratuita hoy.',
    'cta.button': 'Comenzar Ahora',

    // Contact
    'contact.title': 'Contacto',
    'contact.subtitle': 'Hablemos de tu',
    'contact.subtitleHighlight': 'proyecto',
    'contact.description': 'Estamos aquí para ayudarte. Contáctanos y te responderemos en menos de 24 horas.',
    'contact.phone': 'Teléfono',
    'contact.email': 'Email',
    'contact.address': 'Dirección',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.viewLargerMap': 'Ver mapa mas grande',

    // Footer
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Politica de Privacidad',

    // Privacy Policy
    'privacy.title': 'Politica de Privacidad',
    'privacy.back': 'Volver al inicio',
    'privacy.lastUpdated': 'Ultima actualizacion',
    'privacy.intro': 'En Drone Service, nos comprometemos a proteger su privacidad y sus datos personales. Esta politica de privacidad explica como recopilamos, usamos y protegemos su informacion de acuerdo con el Reglamento General de Proteccion de Datos (RGPD) de la Union Europea.',
    'privacy.gdprCompliant': 'Cumplimiento RGPD',
    'privacy.gdprDescription': 'Esta politica cumple con el Reglamento General de Proteccion de Datos (UE) 2016/679',
    'privacy.section1.title': 'Responsable del Tratamiento',
    'privacy.section1.content': 'Drone Service, con domicilio en Ul. Smolna 14, 44-200 Rybnik, Polonia, es el responsable del tratamiento de sus datos personales. Puede contactarnos en admin@drone-partss.com para cualquier consulta relacionada con la privacidad.',
    'privacy.section2.title': 'Datos que Recopilamos',
    'privacy.section2.content': 'Recopilamos los siguientes tipos de datos personales:\n\n- Datos de identificacion: nombre, apellidos, email, telefono\n- Datos de ubicacion: direccion de la finca o terreno para el servicio\n- Datos de servicio: tipo de servicio solicitado, fechas, area de trabajo\n- Datos tecnicos: direccion IP, tipo de navegador, cookies',
    'privacy.section3.title': 'Finalidad del Tratamiento',
    'privacy.section3.content': 'Utilizamos sus datos personales para:\n\n- Gestionar y procesar sus solicitudes de servicios agricolas\n- Comunicarnos con usted sobre el estado de sus servicios\n- Enviar confirmaciones y notificaciones por SMS y email\n- Mejorar nuestros servicios y experiencia de usuario\n- Cumplir con obligaciones legales',
    'privacy.section4.title': 'Base Legal del Tratamiento',
    'privacy.section4.content': 'El tratamiento de sus datos se basa en:\n\n- Su consentimiento explicito al registrarse y solicitar servicios\n- La ejecucion de un contrato de servicios\n- El cumplimiento de obligaciones legales\n- Nuestro interes legitimo en mejorar nuestros servicios',
    'privacy.section5.title': 'Sus Derechos',
    'privacy.section5.content': 'Segun el RGPD, usted tiene derecho a:\n\n- Acceso: solicitar una copia de sus datos personales\n- Rectificacion: corregir datos inexactos o incompletos\n- Supresion: solicitar la eliminacion de sus datos\n- Limitacion: restringir el procesamiento de sus datos\n- Portabilidad: recibir sus datos en formato estructurado\n- Oposicion: oponerse al tratamiento de sus datos\n- Retirar consentimiento: en cualquier momento',
    'privacy.section6.title': 'Conservacion de Datos',
    'privacy.section6.content': 'Conservamos sus datos personales durante el tiempo necesario para cumplir con los fines para los que fueron recopilados, incluyendo requisitos legales, contables o de informes. Generalmente, los datos de clientes se conservan durante 5 años despues del ultimo servicio prestado.',
    'privacy.section7.title': 'Seguridad de los Datos',
    'privacy.section7.content': 'Implementamos medidas tecnicas y organizativas apropiadas para proteger sus datos personales contra el acceso no autorizado, alteracion, divulgacion o destruccion. Esto incluye encriptacion SSL, acceso restringido y copias de seguridad regulares.',
    'privacy.section8.title': 'Contacto y Reclamaciones',
    'privacy.section8.content': 'Para ejercer sus derechos o realizar consultas sobre privacidad, contactenos en admin@drone-partss.com. Si considera que el tratamiento de sus datos vulnera la normativa, puede presentar una reclamacion ante la Agencia de Proteccion de Datos correspondiente.',
    'privacy.contact.title': 'Contacto para Privacidad',
    'privacy.contact.description': 'Si tiene preguntas sobre esta politica o desea ejercer sus derechos:',

    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.back': 'Volver',
    'auth.name': 'Nombre completo',
    'auth.phone': 'Teléfono',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.loginButton': 'Iniciar Sesión',
    'auth.signupButton': 'Crear Cuenta',
    'auth.loggingIn': 'Iniciando sesión...',
    'auth.signingUp': 'Registrando...',
    'auth.continueWith': 'o continúa con',
    'auth.terms': 'Al registrarte, aceptas nuestros',
    'auth.termsLink': 'Términos de Servicio',
    'auth.and': 'y',
    'auth.privacyLink': 'Política de Privacidad',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',

    // Forgot Password
    'forgotPassword.title': 'Recuperar Contraseña',
    'forgotPassword.description': 'Ingresa tu email y te enviaremos instrucciones para restablecer tu contraseña.',
    'forgotPassword.sendButton': 'Enviar Instrucciones',
    'forgotPassword.sending': 'Enviando...',
    'forgotPassword.success': 'Si el email existe, recibirás instrucciones para restablecer tu contraseña.',
    'forgotPassword.error': 'Error al procesar la solicitud',
    'forgotPassword.close': 'Cerrar',

    // Reset Password
    'resetPassword.title': 'Nueva Contraseña',
    'resetPassword.newPassword': 'Nueva contraseña',
    'resetPassword.confirmPassword': 'Confirmar contraseña',
    'resetPassword.resetButton': 'Restablecer Contraseña',
    'resetPassword.resetting': 'Restableciendo...',
    'resetPassword.success': 'Tu contraseña ha sido restablecida correctamente.',
    'resetPassword.goToLogin': 'Ir a Iniciar Sesión',
    'resetPassword.error': 'Error al restablecer la contraseña',
    'resetPassword.minLength': 'La contraseña debe tener al menos 6 caracteres',

    // Dashboard
    'dashboard.title': 'Panel de Cliente',
    'dashboard.welcome': 'Bienvenido',
    'dashboard.logout': 'Cerrar Sesión',
    'dashboard.calendar': 'Calendario',
    'dashboard.jobs': 'Trabajos',
    'dashboard.completed': 'Completados',
    'dashboard.scheduled': 'Programados',
    'dashboard.confirmed': 'Confirmados',
    'dashboard.inProgress': 'En Progreso',
    'dashboard.pending': 'Pendientes',
    'dashboard.all': 'Todos',
    'dashboard.noJobs': 'No hay trabajos registrados',
    'dashboard.requestService': 'Solicitar Servicio',
    'dashboard.status.completed': 'Completado',
    'dashboard.status.scheduled': 'Programado',
    'dashboard.status.confirmed': 'Confirmado',
    'dashboard.status.in_progress': 'En Progreso',
    'dashboard.status.cancelled': 'Cancelado',
    'dashboard.status.pending': 'Pendiente',
    'dashboard.status.inProgress': 'En Progreso',
    'dashboard.jobDetails': 'Detalles del Trabajo',
    'dashboard.date': 'Fecha',
    'dashboard.service': 'Servicio',
    'dashboard.location': 'Ubicación',
    'dashboard.area': 'Área',
    'dashboard.hectares': 'hectáreas',
    'dashboard.today': 'Hoy',
    'dashboard.thisMonth': 'Este Mes',
    'dashboard.upcoming': 'Próximos',
    'dashboard.past': 'Pasados',

    // Service Request Modal
    'serviceRequest.title': 'Solicitar Servicio',
    'serviceRequest.step': 'Paso',
    'serviceRequest.of': 'de',
    'serviceRequest.selectService': '¿Qué servicio necesitas?',
    'serviceRequest.selectDate': 'Selecciona una fecha',
    'serviceRequest.selectTime': 'Selecciona una hora',
    'serviceRequest.form.name': 'Nombre',
    'serviceRequest.form.email': 'Email',
    'serviceRequest.form.phone': 'Teléfono',
    'serviceRequest.form.location': 'Ubicación del terreno',
    'serviceRequest.form.locationPlaceholder': 'Dirección o coordenadas',
    'serviceRequest.form.area': 'Área (hectáreas)',
    'serviceRequest.form.areaPlaceholder': 'Ej: 5',
    'serviceRequest.form.notes': 'Notas adicionales',
    'serviceRequest.form.notesPlaceholder': 'Información adicional sobre el servicio...',
    'serviceRequest.summary': 'Resumen de la solicitud',
    'serviceRequest.summaryService': 'Servicio',
    'serviceRequest.summaryDate': 'Fecha',
    'serviceRequest.summaryTime': 'Hora',
    'serviceRequest.back': 'Atrás',
    'serviceRequest.next': 'Siguiente',
    'serviceRequest.submit': 'Enviar Solicitud',
    'serviceRequest.success.title': '¡Solicitud Enviada!',
    'serviceRequest.success.message': 'Hemos recibido tu solicitud. Te contactaremos en menos de 24 horas para confirmar los detalles.',
    'serviceRequest.success.close': 'Cerrar',
    'serviceRequest.floatingButton': 'Solicitar Servicio',
    'serviceRequest.sending': 'Enviando...',
    'serviceRequest.rental.dateRange': 'Periodo de alquiler',
    'serviceRequest.rental.startDate': 'Fecha de inicio',
    'serviceRequest.rental.endDate': 'Fecha de fin',
    'serviceRequest.rental.totalDays': 'Total de días',
    'serviceRequest.rental.day': 'día',
    'serviceRequest.rental.days': 'días',
    'serviceRequest.rental.pickupTime': 'Hora de recogida',

    // Weather Forecast
    'weather.loading': 'Cargando pronóstico...',
    'weather.errorLoading': 'No se pudo cargar el pronóstico',
    'weather.noForecast': 'Pronóstico no disponible para esta fecha',
    'weather.forecast': 'Pronóstico del tiempo',
    'weather.rentalForecast': 'Pronóstico del periodo',
    'weather.temperature': 'Temperatura',
    'weather.precipitation': 'Prob. lluvia',
    'weather.wind': 'Viento',
    'weather.uvIndex': 'Índice UV',
    'weather.avgTemp': 'Temp. media',
    'weather.maxPrecipProb': 'Máx. prob. lluvia',
    'weather.totalPrecip': 'Precip. total',
    'weather.droneGood': 'Condiciones óptimas para vuelo de drones',
    'weather.droneModerate': 'Condiciones aceptables, revisar antes del vuelo',
    'weather.dronePoor': 'Condiciones desfavorables para vuelo de drones',
    'weather.droneGoodRange': 'Buen clima previsto para el periodo',
    'weather.droneModerateRange': 'Algunas jornadas con condiciones variables',
    'weather.dronePoorRange': 'Se esperan días con mal tiempo',
    'weather.sunny': 'Soleado',
    'weather.lightClouds': 'Poco nuboso',
    'weather.partlyCloudy': 'Parcialmente nublado',
    'weather.cloudy': 'Nublado',
    'weather.rain': 'Lluvia',
    'weather.rainSnow': 'Lluvia y nieve',
    'weather.snow': 'Nieve',
    'weather.rainSnowShowers': 'Chubascos de nieve',
    'weather.foggy': 'Niebla',
    'weather.lightRain': 'Lluvia ligera',
    'weather.heavyRain': 'Lluvia intensa',
    'weather.lightSnow': 'Nevada ligera',
    'weather.heavySnow': 'Nevada intensa',
    'weather.rainShowers': 'Chubascos',
    'weather.snowShowers': 'Chubascos de nieve',
    'weather.thunderstorm': 'Tormenta',
    'weather.hail': 'Granizo',
    'weather.unknown': 'Desconocido',

    // Admin Dashboard
    'admin.title': 'Panel de Administración',
    'admin.subtitle': 'Gestiona todas las solicitudes de servicio',
    'admin.requests': 'Solicitudes de Servicio',
    'admin.noRequests': 'No hay solicitudes',
    'admin.confirm': 'Confirmar',
    'admin.complete': 'Completar',
    'admin.startWork': 'Iniciar Trabajo',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.confirmDelete': 'Confirmar',
    'admin.refresh': 'Actualizar',
    'admin.statusError': 'Error al actualizar estado',
    'admin.deleteError': 'Error al eliminar solicitud',
    'admin.viewDetails': 'Ver Detalles',
    'admin.smsSent': 'SMS enviado al cliente',
    'admin.smsError': 'Error al enviar SMS',
    'admin.sendingSms': 'Enviando SMS...',
    'admin.notificationsSent': 'SMS y Email enviados',
    'admin.notificationsError': 'Error al enviar notificaciones',

    // Password Management
    'admin.passwordManagement': 'Gestión de Contraseñas',
    'admin.changeOwnPassword': 'Cambiar Mi Contraseña',
    'admin.userAccounts': 'Cuentas de Usuario',
    'admin.currentPassword': 'Contraseña actual',
    'admin.newPassword': 'Nueva contraseña',
    'admin.confirmNewPassword': 'Confirmar nueva contraseña',
    'admin.changePassword': 'Cambiar Contraseña',
    'admin.passwordChanged': 'Contraseña cambiada correctamente',
    'admin.userPasswordChanged': 'Contraseña del usuario cambiada correctamente',
    'admin.passwordError': 'Error al cambiar la contraseña',
    'admin.noUsers': 'No hay usuarios registrados',

    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Configura las APIs de SMS y Email',
    'settings.backToAdmin': 'Volver al Panel',
    'settings.vonageTitle': 'Configuración de Vonage SMS',
    'settings.vonageSubtitle': 'Configura las credenciales de la API de Vonage para enviar SMS.',
    'settings.smtpTitle': 'Configuración de Email SMTP',
    'settings.smtpSubtitle': 'Configura el servidor SMTP para enviar emails de confirmación.',
    'settings.smtpHost': 'Servidor SMTP',
    'settings.smtpPort': 'Puerto',
    'settings.smtpUser': 'Usuario SMTP',
    'settings.smtpPass': 'Contraseña',
    'settings.smtpPassHint': 'Para Gmail, usa una contraseña de aplicación',
    'settings.fromNumber': 'Nombre/Número del remitente',
    'settings.fromEmail': 'Email del remitente',
    'settings.configured': 'Configurado',
    'settings.notConfigured': 'No configurado',
    'settings.save': 'Guardar',
    'settings.test': 'Probar',
    'settings.vonageSaved': 'Configuración de Vonage guardada',
    'settings.smtpSaved': 'Configuración SMTP guardada',
    'settings.saveError': 'Error al guardar',
    'settings.vonageTestSuccess': 'Conexión con Vonage exitosa',
    'settings.vonageTestError': 'Error al conectar con Vonage',
    'settings.smtpTestSuccess': 'Conexión SMTP exitosa',
    'settings.smtpTestError': 'Error al conectar con SMTP',
    'settings.testSms': 'Enviar SMS de prueba',
    'settings.testPhone': 'Número de teléfono',
    'settings.testPhoneHint': 'Incluye el código de país (+48...)',
    'settings.sendTestSms': 'Enviar SMS',
    'settings.enterTestPhone': 'Ingresa un número de teléfono',
    'settings.smsTestSuccess': 'SMS enviado correctamente',
    'settings.smsTestError': 'Error al enviar SMS',
    'settings.keepExisting': 'Dejar vacío para mantener valor actual',
    'settings.testEmail': 'Enviar Email de prueba',
    'settings.testEmailAddress': 'Dirección de email',
    'settings.sendTestEmail': 'Enviar Email',
    'settings.enterTestEmail': 'Ingresa una dirección de email',
    'settings.emailTestSuccess': 'Email enviado correctamente',
    'settings.emailTestError': 'Error al enviar email',
  },
  pl: {
    // Navigation
    'nav.services': 'Usługi',
    'nav.about': 'O nas',
    'nav.contact': 'Kontakt',
    'nav.privacy': 'Prywatnosc',
    'nav.start': 'Rozpocznij',

    // Hero
    'hero.badge': 'Rolnictwo Przyszłości',
    'hero.title1': 'Przekształć swoje',
    'hero.title2': 'Rolnictwo z Dronami',
    'hero.description': 'Usługi precyzyjnego rolnictwa z najnowocześniejszą technologią. Zmaksymalizuj wydajność swoich upraw dzięki inteligentnym rozwiązaniom.',
    'hero.cta': 'Zamów Usługę',
    'hero.viewServices': 'Zobacz Usługi',

    // Stats
    'stats.hectares': 'Hektarów Obsłużonych',
    'stats.precision': 'Precyzja',
    'stats.response': 'Czas Odpowiedzi',
    'stats.clients': 'Klientów',

    // Services
    'services.title': 'Nasze Usługi',
    'services.subtitle': 'Rozwiązania',
    'services.subtitleHighlight': 'Rolnicze',
    'service.fumigation.title': 'Opryski Dronem',
    'service.fumigation.desc': 'Precyzyjne stosowanie środków ochrony roślin z wykorzystaniem najnowszej technologii.',
    'service.painting.title': 'Malowanie Szklarni',
    'service.painting.desc': 'Ochrona UV i kontrola klimatu dla optymalizacji wzrostu upraw.',
    'service.mapping.title': 'Mapowanie Lotnicze',
    'service.mapping.desc': 'Szczegółowa analiza terenu z obrazami wysokiej rozdzielczości i precyzyjnymi danymi.',
    'service.elevation.title': 'Modele Wysokościowe',
    'service.elevation.desc': 'Planowanie nawadniania i drenażu z precyzyjnymi modelami topograficznymi 3D.',
    'service.rental.title': 'Wynajem Dronów',
    'service.rental.desc': 'Wynajem profesjonalnych dronów rolniczych z operatorem lub bez do Twoich projektów.',

    // About
    'about.title': 'O Nas',
    'about.subtitle': 'Innowacja w służbie',
    'about.subtitleHighlight': 'rolnictwa',
    'about.description': 'Jesteśmy pionierami w stosowaniu technologii dronów w rolnictwie. Nasz zespół ekspertów łączy wiedzę rolniczą z najnowocześniejszą technologią, oferując rozwiązania transformujące produktywność Twojego pola.',
    'about.feature1': 'Najnowocześniejsza technologia',
    'about.feature2': 'Certyfikowany zespół ekspertów',
    'about.feature3': 'Zaangażowanie w ochronę środowiska',
    'about.feature4': 'Gwarantowane rezultaty',
    'about.years': 'Lat Doświadczenia',
    'about.drones': 'Dronów we Flocie',
    'about.support': 'Wsparcie Techniczne',
    'about.satisfaction': 'Satysfakcja',

    // CTA
    'cta.title': 'Gotowy na',
    'cta.titleHighlight': 'transformację',
    'cta.titleEnd': 'swojego rolnictwa?',
    'cta.description': 'Dołącz do setek rolników, którzy już korzystają z mocy dronów. Zamów bezpłatną pierwszą konsultację już dziś.',
    'cta.button': 'Rozpocznij Teraz',

    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Porozmawiajmy o Twoim',
    'contact.subtitleHighlight': 'projekcie',
    'contact.description': 'Jesteśmy tutaj, aby Ci pomóc. Skontaktuj się z nami, a odpowiemy w ciągu 24 godzin.',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.address': 'Adres',
    'contact.form.name': 'Imię',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Temat',
    'contact.form.message': 'Wiadomość',
    'contact.form.send': 'Wyślij Wiadomość',
    'contact.viewLargerMap': 'Zobacz wieksza mape',

    // Footer
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.privacy': 'Polityka Prywatnosci',

    // Privacy Policy
    'privacy.title': 'Polityka Prywatnosci',
    'privacy.back': 'Powrot do strony glownej',
    'privacy.lastUpdated': 'Ostatnia aktualizacja',
    'privacy.intro': 'W Drone Service zobowiazujemy sie do ochrony Twojej prywatnosci i danych osobowych. Niniejsza polityka prywatnosci wyjasnia, w jaki sposob zbieramy, wykorzystujemy i chronimy Twoje informacje zgodnie z Ogolnym Rozporzadzeniem o Ochronie Danych (RODO) Unii Europejskiej.',
    'privacy.gdprCompliant': 'Zgodnosc z RODO',
    'privacy.gdprDescription': 'Niniejsza polityka jest zgodna z Ogolnym Rozporzadzeniem o Ochronie Danych (UE) 2016/679',
    'privacy.section1.title': 'Administrator Danych',
    'privacy.section1.content': 'Drone Service z siedziba przy Ul. Smolna 14, 44-200 Rybnik, Polska, jest administratorem Twoich danych osobowych. Mozesz sie z nami skontaktowac pod adresem admin@drone-partss.com w sprawie wszelkich pytan dotyczacych prywatnosci.',
    'privacy.section2.title': 'Dane, ktore Zbieramy',
    'privacy.section2.content': 'Zbieramy nastepujace rodzaje danych osobowych:\n\n- Dane identyfikacyjne: imie, nazwisko, email, telefon\n- Dane lokalizacyjne: adres gospodarstwa lub terenu do obslugi\n- Dane uslugowe: rodzaj zamowionej uslugi, daty, obszar pracy\n- Dane techniczne: adres IP, typ przegladarki, pliki cookie',
    'privacy.section3.title': 'Cel Przetwarzania',
    'privacy.section3.content': 'Wykorzystujemy Twoje dane osobowe do:\n\n- Zarzadzania i przetwarzania zamowien na uslugi rolnicze\n- Komunikacji z Toba w sprawie statusu uslug\n- Wysylania potwierdzen i powiadomien SMS i email\n- Poprawy naszych uslug i doswiadczenia uzytkownika\n- Spelniania obowiazkow prawnych',
    'privacy.section4.title': 'Podstawa Prawna Przetwarzania',
    'privacy.section4.content': 'Przetwarzanie Twoich danych opiera sie na:\n\n- Twojej wyraznej zgodzie przy rejestracji i zamawianiu uslug\n- Wykonaniu umowy o swiadczenie uslug\n- Spelnieniu obowiazkow prawnych\n- Naszym uzasadnionym interesie w poprawie naszych uslug',
    'privacy.section5.title': 'Twoje Prawa',
    'privacy.section5.content': 'Zgodnie z RODO masz prawo do:\n\n- Dostepu: zadania kopii swoich danych osobowych\n- Sprostowania: poprawienia niedokladnych lub niekompletnych danych\n- Usuniecia: zadania usuniecia swoich danych\n- Ograniczenia: ograniczenia przetwarzania swoich danych\n- Przenoszenia: otrzymania swoich danych w ustrukturyzowanym formacie\n- Sprzeciwu: sprzeciwienia sie przetwarzaniu swoich danych\n- Wycofania zgody: w dowolnym momencie',
    'privacy.section6.title': 'Przechowywanie Danych',
    'privacy.section6.content': 'Przechowujemy Twoje dane osobowe przez okres niezbedny do realizacji celow, dla ktorych zostaly zebrane, w tym wymagan prawnych, ksiegowych lub sprawozdawczych. Ogolnie dane klientow sa przechowywane przez 5 lat po ostatniej swiadczonej usludze.',
    'privacy.section7.title': 'Bezpieczenstwo Danych',
    'privacy.section7.content': 'Wdrazamy odpowiednie srodki techniczne i organizacyjne w celu ochrony Twoich danych osobowych przed nieuprawnionym dostepem, zmiana, ujawnieniem lub zniszczeniem. Obejmuje to szyfrowanie SSL, ograniczony dostep i regularne kopie zapasowe.',
    'privacy.section8.title': 'Kontakt i Skargi',
    'privacy.section8.content': 'Aby skorzystac ze swoich praw lub uzyskac informacje o prywatnosci, skontaktuj sie z nami pod adresem admin@drone-partss.com. Jesli uwazasz, ze przetwarzanie Twoich danych narusza przepisy, mozesz zlozyc skarge do odpowiedniego organu ochrony danych.',
    'privacy.contact.title': 'Kontakt w Sprawie Prywatnosci',
    'privacy.contact.description': 'Jesli masz pytania dotyczace tej polityki lub chcesz skorzystac ze swoich praw:',

    // Auth
    'auth.login': 'Zaloguj się',
    'auth.signup': 'Zarejestruj się',
    'auth.back': 'Wróć',
    'auth.name': 'Pełne imię i nazwisko',
    'auth.phone': 'Telefon',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.confirmPassword': 'Potwierdź hasło',
    'auth.forgotPassword': 'Zapomniałeś hasła?',
    'auth.loginButton': 'Zaloguj się',
    'auth.signupButton': 'Utwórz Konto',
    'auth.loggingIn': 'Logowanie...',
    'auth.signingUp': 'Rejestracja...',
    'auth.continueWith': 'lub kontynuuj z',
    'auth.terms': 'Rejestrując się, akceptujesz nasze',
    'auth.termsLink': 'Warunki Usługi',
    'auth.and': 'i',
    'auth.privacyLink': 'Politykę Prywatności',
    'auth.passwordMismatch': 'Hasła nie pasują do siebie',

    // Forgot Password
    'forgotPassword.title': 'Odzyskaj Hasło',
    'forgotPassword.description': 'Wpisz swój email, a wyślemy Ci instrukcje resetowania hasła.',
    'forgotPassword.sendButton': 'Wyślij Instrukcje',
    'forgotPassword.sending': 'Wysyłanie...',
    'forgotPassword.success': 'Jeśli email istnieje, otrzymasz instrukcje resetowania hasła.',
    'forgotPassword.error': 'Błąd podczas przetwarzania żądania',
    'forgotPassword.close': 'Zamknij',

    // Reset Password
    'resetPassword.title': 'Nowe Hasło',
    'resetPassword.newPassword': 'Nowe hasło',
    'resetPassword.confirmPassword': 'Potwierdź hasło',
    'resetPassword.resetButton': 'Zresetuj Hasło',
    'resetPassword.resetting': 'Resetowanie...',
    'resetPassword.success': 'Twoje hasło zostało pomyślnie zresetowane.',
    'resetPassword.goToLogin': 'Przejdź do Logowania',
    'resetPassword.error': 'Błąd podczas resetowania hasła',
    'resetPassword.minLength': 'Hasło musi mieć co najmniej 6 znaków',

    // Dashboard
    'dashboard.title': 'Panel Klienta',
    'dashboard.welcome': 'Witaj',
    'dashboard.logout': 'Wyloguj się',
    'dashboard.calendar': 'Kalendarz',
    'dashboard.jobs': 'Prace',
    'dashboard.completed': 'Zakończone',
    'dashboard.scheduled': 'Zaplanowane',
    'dashboard.confirmed': 'Potwierdzone',
    'dashboard.inProgress': 'W Trakcie',
    'dashboard.pending': 'Oczekujące',
    'dashboard.all': 'Wszystkie',
    'dashboard.noJobs': 'Brak zarejestrowanych prac',
    'dashboard.requestService': 'Zamów Usługę',
    'dashboard.status.completed': 'Zakończone',
    'dashboard.status.scheduled': 'Zaplanowane',
    'dashboard.status.confirmed': 'Potwierdzone',
    'dashboard.status.in_progress': 'W Trakcie',
    'dashboard.status.cancelled': 'Anulowane',
    'dashboard.status.pending': 'Oczekujące',
    'dashboard.status.inProgress': 'W Trakcie',
    'dashboard.jobDetails': 'Szczegóły Pracy',
    'dashboard.date': 'Data',
    'dashboard.service': 'Usługa',
    'dashboard.location': 'Lokalizacja',
    'dashboard.area': 'Powierzchnia',
    'dashboard.hectares': 'hektarów',
    'dashboard.today': 'Dziś',
    'dashboard.thisMonth': 'Ten Miesiąc',
    'dashboard.upcoming': 'Nadchodzące',
    'dashboard.past': 'Przeszłe',

    // Service Request Modal
    'serviceRequest.title': 'Zamów Usługę',
    'serviceRequest.step': 'Krok',
    'serviceRequest.of': 'z',
    'serviceRequest.selectService': 'Jakiej usługi potrzebujesz?',
    'serviceRequest.selectDate': 'Wybierz datę',
    'serviceRequest.selectTime': 'Wybierz godzinę',
    'serviceRequest.form.name': 'Imię',
    'serviceRequest.form.email': 'Email',
    'serviceRequest.form.phone': 'Telefon',
    'serviceRequest.form.location': 'Lokalizacja terenu',
    'serviceRequest.form.locationPlaceholder': 'Adres lub współrzędne',
    'serviceRequest.form.area': 'Powierzchnia (hektary)',
    'serviceRequest.form.areaPlaceholder': 'Np: 5',
    'serviceRequest.form.notes': 'Dodatkowe uwagi',
    'serviceRequest.form.notesPlaceholder': 'Dodatkowe informacje o usłudze...',
    'serviceRequest.summary': 'Podsumowanie zamówienia',
    'serviceRequest.summaryService': 'Usługa',
    'serviceRequest.summaryDate': 'Data',
    'serviceRequest.summaryTime': 'Godzina',
    'serviceRequest.back': 'Wstecz',
    'serviceRequest.next': 'Dalej',
    'serviceRequest.submit': 'Wyślij Zamówienie',
    'serviceRequest.success.title': 'Zamówienie Wysłane!',
    'serviceRequest.success.message': 'Otrzymaliśmy Twoje zamówienie. Skontaktujemy się z Tobą w ciągu 24 godzin, aby potwierdzić szczegóły.',
    'serviceRequest.success.close': 'Zamknij',
    'serviceRequest.floatingButton': 'Zamów Usługę',
    'serviceRequest.sending': 'Wysyłanie...',
    'serviceRequest.rental.dateRange': 'Okres wynajmu',
    'serviceRequest.rental.startDate': 'Data rozpoczęcia',
    'serviceRequest.rental.endDate': 'Data zakończenia',
    'serviceRequest.rental.totalDays': 'Łączna liczba dni',
    'serviceRequest.rental.day': 'dzień',
    'serviceRequest.rental.days': 'dni',
    'serviceRequest.rental.pickupTime': 'Godzina odbioru',

    // Weather Forecast
    'weather.loading': 'Ładowanie prognozy...',
    'weather.errorLoading': 'Nie udało się załadować prognozy',
    'weather.noForecast': 'Prognoza niedostępna dla tej daty',
    'weather.forecast': 'Prognoza pogody',
    'weather.rentalForecast': 'Prognoza na okres',
    'weather.temperature': 'Temperatura',
    'weather.precipitation': 'Szansa opadów',
    'weather.wind': 'Wiatr',
    'weather.uvIndex': 'Indeks UV',
    'weather.avgTemp': 'Śr. temp.',
    'weather.maxPrecipProb': 'Maks. szansa opadów',
    'weather.totalPrecip': 'Suma opadów',
    'weather.droneGood': 'Optymalne warunki do lotu dronem',
    'weather.droneModerate': 'Akceptowalne warunki, sprawdź przed lotem',
    'weather.dronePoor': 'Niekorzystne warunki do lotu dronem',
    'weather.droneGoodRange': 'Dobra pogoda przewidziana na okres',
    'weather.droneModerateRange': 'Niektóre dni ze zmiennymi warunkami',
    'weather.dronePoorRange': 'Spodziewane dni ze złą pogodą',
    'weather.sunny': 'Słonecznie',
    'weather.lightClouds': 'Lekkie zachmurzenie',
    'weather.partlyCloudy': 'Częściowe zachmurzenie',
    'weather.cloudy': 'Pochmurno',
    'weather.rain': 'Deszcz',
    'weather.rainSnow': 'Deszcz ze śniegiem',
    'weather.snow': 'Śnieg',
    'weather.rainSnowShowers': 'Przelotny śnieg',
    'weather.foggy': 'Mgła',
    'weather.lightRain': 'Lekki deszcz',
    'weather.heavyRain': 'Intensywny deszcz',
    'weather.lightSnow': 'Lekki śnieg',
    'weather.heavySnow': 'Intensywne opady śniegu',
    'weather.rainShowers': 'Przelotne opady',
    'weather.snowShowers': 'Przelotny śnieg',
    'weather.thunderstorm': 'Burza',
    'weather.hail': 'Grad',
    'weather.unknown': 'Nieznane',

    // Admin Dashboard
    'admin.title': 'Panel Administracyjny',
    'admin.subtitle': 'Zarządzaj wszystkimi zamówieniami usług',
    'admin.requests': 'Zamówienia Usług',
    'admin.noRequests': 'Brak zamówień',
    'admin.confirm': 'Potwierdź',
    'admin.complete': 'Zakończ',
    'admin.startWork': 'Rozpocznij Pracę',
    'admin.cancel': 'Anuluj',
    'admin.delete': 'Usuń',
    'admin.confirmDelete': 'Potwierdź',
    'admin.refresh': 'Odśwież',
    'admin.statusError': 'Błąd aktualizacji statusu',
    'admin.deleteError': 'Błąd usuwania zamówienia',
    'admin.viewDetails': 'Zobacz Szczegóły',
    'admin.smsSent': 'SMS wysłany do klienta',
    'admin.smsError': 'Błąd wysyłania SMS',
    'admin.sendingSms': 'Wysyłanie SMS...',
    'admin.notificationsSent': 'SMS i Email wysłane',
    'admin.notificationsError': 'Błąd wysyłania powiadomień',

    // Password Management
    'admin.passwordManagement': 'Zarządzanie Hasłami',
    'admin.changeOwnPassword': 'Zmień Moje Hasło',
    'admin.userAccounts': 'Konta Użytkowników',
    'admin.currentPassword': 'Aktualne hasło',
    'admin.newPassword': 'Nowe hasło',
    'admin.confirmNewPassword': 'Potwierdź nowe hasło',
    'admin.changePassword': 'Zmień Hasło',
    'admin.passwordChanged': 'Hasło zostało zmienione',
    'admin.userPasswordChanged': 'Hasło użytkownika zostało zmienione',
    'admin.passwordError': 'Błąd podczas zmiany hasła',
    'admin.noUsers': 'Brak zarejestrowanych użytkowników',

    // Settings
    'settings.title': 'Ustawienia',
    'settings.subtitle': 'Skonfiguruj API SMS i Email',
    'settings.backToAdmin': 'Powrót do Panelu',
    'settings.vonageTitle': 'Konfiguracja Vonage SMS',
    'settings.vonageSubtitle': 'Skonfiguruj dane uwierzytelniające API Vonage do wysyłania SMS.',
    'settings.smtpTitle': 'Konfiguracja Email SMTP',
    'settings.smtpSubtitle': 'Skonfiguruj serwer SMTP do wysyłania emaili potwierdzających.',
    'settings.smtpHost': 'Serwer SMTP',
    'settings.smtpPort': 'Port',
    'settings.smtpUser': 'Użytkownik SMTP',
    'settings.smtpPass': 'Hasło',
    'settings.smtpPassHint': 'Dla Gmail użyj hasła aplikacji',
    'settings.fromNumber': 'Nazwa/Numer nadawcy',
    'settings.fromEmail': 'Email nadawcy',
    'settings.configured': 'Skonfigurowany',
    'settings.notConfigured': 'Nie skonfigurowany',
    'settings.save': 'Zapisz',
    'settings.test': 'Testuj',
    'settings.vonageSaved': 'Konfiguracja Vonage zapisana',
    'settings.smtpSaved': 'Konfiguracja SMTP zapisana',
    'settings.saveError': 'Błąd zapisu',
    'settings.vonageTestSuccess': 'Połączenie z Vonage udane',
    'settings.vonageTestError': 'Błąd połączenia z Vonage',
    'settings.smtpTestSuccess': 'Połączenie SMTP udane',
    'settings.smtpTestError': 'Błąd połączenia SMTP',
    'settings.testSms': 'Wyślij testowy SMS',
    'settings.testPhone': 'Numer telefonu',
    'settings.testPhoneHint': 'Włącz kod kraju (+48...)',
    'settings.sendTestSms': 'Wyślij SMS',
    'settings.enterTestPhone': 'Wprowadź numer telefonu',
    'settings.smsTestSuccess': 'SMS wysłany pomyślnie',
    'settings.smsTestError': 'Błąd wysyłania SMS',
    'settings.keepExisting': 'Pozostaw puste, aby zachować aktualną wartość',
    'settings.testEmail': 'Wyślij testowy Email',
    'settings.testEmailAddress': 'Adres email',
    'settings.sendTestEmail': 'Wyślij Email',
    'settings.enterTestEmail': 'Wprowadź adres email',
    'settings.emailTestSuccess': 'Email wysłany pomyślnie',
    'settings.emailTestError': 'Błąd wysyłania email',
  },
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.privacy': 'Privacy',
    'nav.start': 'Get Started',

    // Hero
    'hero.badge': 'Agriculture of the Future',
    'hero.title1': 'Transform your',
    'hero.title2': 'Agriculture with Drones',
    'hero.description': 'Precision agriculture services with cutting-edge technology. Maximize your crop yields with smart solutions.',
    'hero.cta': 'Request Service',
    'hero.viewServices': 'View Services',

    // Stats
    'stats.hectares': 'Hectares Treated',
    'stats.precision': 'Precision',
    'stats.response': 'Response',
    'stats.clients': 'Clients',

    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Agricultural',
    'services.subtitleHighlight': 'Solutions',
    'service.fumigation.title': 'Drone Fumigation',
    'service.fumigation.desc': 'Precise application of phytosanitary treatments with state-of-the-art technology.',
    'service.painting.title': 'Greenhouse Painting',
    'service.painting.desc': 'UV protection and climate control to optimize your crop growth.',
    'service.mapping.title': 'Aerial Mapping',
    'service.mapping.desc': 'Detailed terrain analysis with high-resolution images and precise data.',
    'service.elevation.title': 'Elevation Models',
    'service.elevation.desc': 'Irrigation and drainage planning with high-precision 3D topographic models.',
    'service.rental.title': 'Drone Rental',
    'service.rental.desc': 'Professional agricultural drone rental with or without operator for your projects.',

    // About
    'about.title': 'About Us',
    'about.subtitle': 'Innovation at the service of',
    'about.subtitleHighlight': 'farming',
    'about.description': 'We are pioneers in applying drone technology to agriculture. Our team of experts combines agricultural knowledge with cutting-edge technology to offer solutions that transform your field productivity.',
    'about.feature1': 'State-of-the-art technology',
    'about.feature2': 'Certified expert team',
    'about.feature3': 'Environmental commitment',
    'about.feature4': 'Guaranteed results',
    'about.years': 'Years of Experience',
    'about.drones': 'Drones in Fleet',
    'about.support': 'Technical Support',
    'about.satisfaction': 'Satisfaction',

    // CTA
    'cta.title': 'Ready to',
    'cta.titleHighlight': 'transform',
    'cta.titleEnd': 'your agriculture?',
    'cta.description': 'Join hundreds of farmers who are already harnessing the power of drones. Request your free first consultation today.',
    'cta.button': 'Start Now',

    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': "Let's talk about your",
    'contact.subtitleHighlight': 'project',
    'contact.description': "We're here to help. Contact us and we'll respond within 24 hours.",
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.viewLargerMap': 'View larger map',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.back': 'Back to home',
    'privacy.lastUpdated': 'Last updated',
    'privacy.intro': 'At Drone Service, we are committed to protecting your privacy and personal data. This privacy policy explains how we collect, use, and protect your information in accordance with the General Data Protection Regulation (GDPR) of the European Union.',
    'privacy.gdprCompliant': 'GDPR Compliant',
    'privacy.gdprDescription': 'This policy complies with the General Data Protection Regulation (EU) 2016/679',
    'privacy.section1.title': 'Data Controller',
    'privacy.section1.content': 'Drone Service, located at Ul. Smolna 14, 44-200 Rybnik, Poland, is the data controller for your personal data. You can contact us at admin@drone-partss.com for any privacy-related inquiries.',
    'privacy.section2.title': 'Data We Collect',
    'privacy.section2.content': 'We collect the following types of personal data:\n\n- Identification data: name, surname, email, phone\n- Location data: farm or field address for service\n- Service data: type of service requested, dates, work area\n- Technical data: IP address, browser type, cookies',
    'privacy.section3.title': 'Purpose of Processing',
    'privacy.section3.content': 'We use your personal data to:\n\n- Manage and process your agricultural service requests\n- Communicate with you about the status of your services\n- Send confirmations and notifications via SMS and email\n- Improve our services and user experience\n- Comply with legal obligations',
    'privacy.section4.title': 'Legal Basis for Processing',
    'privacy.section4.content': 'The processing of your data is based on:\n\n- Your explicit consent when registering and requesting services\n- The execution of a service contract\n- Compliance with legal obligations\n- Our legitimate interest in improving our services',
    'privacy.section5.title': 'Your Rights',
    'privacy.section5.content': 'Under the GDPR, you have the right to:\n\n- Access: request a copy of your personal data\n- Rectification: correct inaccurate or incomplete data\n- Erasure: request deletion of your data\n- Restriction: restrict the processing of your data\n- Portability: receive your data in a structured format\n- Objection: object to the processing of your data\n- Withdraw consent: at any time',
    'privacy.section6.title': 'Data Retention',
    'privacy.section6.content': 'We retain your personal data for as long as necessary to fulfill the purposes for which it was collected, including legal, accounting, or reporting requirements. Generally, customer data is retained for 5 years after the last service provided.',
    'privacy.section7.title': 'Data Security',
    'privacy.section7.content': 'We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. This includes SSL encryption, restricted access, and regular backups.',
    'privacy.section8.title': 'Contact and Complaints',
    'privacy.section8.content': 'To exercise your rights or make privacy inquiries, contact us at admin@drone-partss.com. If you believe that the processing of your data violates regulations, you can file a complaint with the relevant Data Protection Authority.',
    'privacy.contact.title': 'Privacy Contact',
    'privacy.contact.description': 'If you have questions about this policy or wish to exercise your rights:',

    // Auth
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.back': 'Back',
    'auth.name': 'Full name',
    'auth.phone': 'Phone',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.loginButton': 'Log In',
    'auth.signupButton': 'Create Account',
    'auth.loggingIn': 'Logging in...',
    'auth.signingUp': 'Signing up...',
    'auth.continueWith': 'or continue with',
    'auth.terms': 'By signing up, you agree to our',
    'auth.termsLink': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacyLink': 'Privacy Policy',
    'auth.passwordMismatch': 'Passwords do not match',

    // Forgot Password
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.description': 'Enter your email and we will send you instructions to reset your password.',
    'forgotPassword.sendButton': 'Send Instructions',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.success': 'If the email exists, you will receive instructions to reset your password.',
    'forgotPassword.error': 'Error processing request',
    'forgotPassword.close': 'Close',

    // Reset Password
    'resetPassword.title': 'New Password',
    'resetPassword.newPassword': 'New password',
    'resetPassword.confirmPassword': 'Confirm password',
    'resetPassword.resetButton': 'Reset Password',
    'resetPassword.resetting': 'Resetting...',
    'resetPassword.success': 'Your password has been successfully reset.',
    'resetPassword.goToLogin': 'Go to Login',
    'resetPassword.error': 'Error resetting password',
    'resetPassword.minLength': 'Password must be at least 6 characters',

    // Dashboard
    'dashboard.title': 'Client Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.logout': 'Log Out',
    'dashboard.calendar': 'Calendar',
    'dashboard.jobs': 'Jobs',
    'dashboard.completed': 'Completed',
    'dashboard.scheduled': 'Scheduled',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.inProgress': 'In Progress',
    'dashboard.pending': 'Pending',
    'dashboard.all': 'All',
    'dashboard.noJobs': 'No jobs registered',
    'dashboard.requestService': 'Request Service',
    'dashboard.status.completed': 'Completed',
    'dashboard.status.scheduled': 'Scheduled',
    'dashboard.status.confirmed': 'Confirmed',
    'dashboard.status.in_progress': 'In Progress',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.status.pending': 'Pending',
    'dashboard.status.inProgress': 'In Progress',
    'dashboard.jobDetails': 'Job Details',
    'dashboard.date': 'Date',
    'dashboard.service': 'Service',
    'dashboard.location': 'Location',
    'dashboard.area': 'Area',
    'dashboard.hectares': 'hectares',
    'dashboard.today': 'Today',
    'dashboard.thisMonth': 'This Month',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.past': 'Past',

    // Service Request Modal
    'serviceRequest.title': 'Request Service',
    'serviceRequest.step': 'Step',
    'serviceRequest.of': 'of',
    'serviceRequest.selectService': 'What service do you need?',
    'serviceRequest.selectDate': 'Select a date',
    'serviceRequest.selectTime': 'Select a time',
    'serviceRequest.form.name': 'Name',
    'serviceRequest.form.email': 'Email',
    'serviceRequest.form.phone': 'Phone',
    'serviceRequest.form.location': 'Field location',
    'serviceRequest.form.locationPlaceholder': 'Address or coordinates',
    'serviceRequest.form.area': 'Area (hectares)',
    'serviceRequest.form.areaPlaceholder': 'E.g.: 5',
    'serviceRequest.form.notes': 'Additional notes',
    'serviceRequest.form.notesPlaceholder': 'Additional information about the service...',
    'serviceRequest.summary': 'Request summary',
    'serviceRequest.summaryService': 'Service',
    'serviceRequest.summaryDate': 'Date',
    'serviceRequest.summaryTime': 'Time',
    'serviceRequest.back': 'Back',
    'serviceRequest.next': 'Next',
    'serviceRequest.submit': 'Submit Request',
    'serviceRequest.success.title': 'Request Sent!',
    'serviceRequest.success.message': 'We have received your request. We will contact you within 24 hours to confirm the details.',
    'serviceRequest.success.close': 'Close',
    'serviceRequest.floatingButton': 'Request Service',
    'serviceRequest.sending': 'Sending...',
    'serviceRequest.rental.dateRange': 'Rental period',
    'serviceRequest.rental.startDate': 'Start date',
    'serviceRequest.rental.endDate': 'End date',
    'serviceRequest.rental.totalDays': 'Total days',
    'serviceRequest.rental.day': 'day',
    'serviceRequest.rental.days': 'days',
    'serviceRequest.rental.pickupTime': 'Pickup time',

    // Weather Forecast
    'weather.loading': 'Loading forecast...',
    'weather.errorLoading': 'Could not load forecast',
    'weather.noForecast': 'Forecast not available for this date',
    'weather.forecast': 'Weather Forecast',
    'weather.rentalForecast': 'Period Forecast',
    'weather.temperature': 'Temperature',
    'weather.precipitation': 'Rain chance',
    'weather.wind': 'Wind',
    'weather.uvIndex': 'UV Index',
    'weather.avgTemp': 'Avg temp',
    'weather.maxPrecipProb': 'Max rain chance',
    'weather.totalPrecip': 'Total precip',
    'weather.droneGood': 'Optimal conditions for drone flight',
    'weather.droneModerate': 'Acceptable conditions, check before flight',
    'weather.dronePoor': 'Unfavorable conditions for drone flight',
    'weather.droneGoodRange': 'Good weather expected for the period',
    'weather.droneModerateRange': 'Some days with variable conditions',
    'weather.dronePoorRange': 'Bad weather days expected',
    'weather.sunny': 'Sunny',
    'weather.lightClouds': 'Light clouds',
    'weather.partlyCloudy': 'Partly cloudy',
    'weather.cloudy': 'Cloudy',
    'weather.rain': 'Rain',
    'weather.rainSnow': 'Rain and snow',
    'weather.snow': 'Snow',
    'weather.rainSnowShowers': 'Snow showers',
    'weather.foggy': 'Foggy',
    'weather.lightRain': 'Light rain',
    'weather.heavyRain': 'Heavy rain',
    'weather.lightSnow': 'Light snow',
    'weather.heavySnow': 'Heavy snow',
    'weather.rainShowers': 'Rain showers',
    'weather.snowShowers': 'Snow showers',
    'weather.thunderstorm': 'Thunderstorm',
    'weather.hail': 'Hail',
    'weather.unknown': 'Unknown',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage all service requests',
    'admin.requests': 'Service Requests',
    'admin.noRequests': 'No requests',
    'admin.confirm': 'Confirm',
    'admin.complete': 'Complete',
    'admin.startWork': 'Start Work',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.confirmDelete': 'Confirm',
    'admin.refresh': 'Refresh',
    'admin.statusError': 'Error updating status',
    'admin.deleteError': 'Error deleting request',
    'admin.viewDetails': 'View Details',
    'admin.smsSent': 'SMS sent to client',
    'admin.smsError': 'Error sending SMS',
    'admin.sendingSms': 'Sending SMS...',
    'admin.notificationsSent': 'SMS and Email sent',
    'admin.notificationsError': 'Error sending notifications',

    // Password Management
    'admin.passwordManagement': 'Password Management',
    'admin.changeOwnPassword': 'Change My Password',
    'admin.userAccounts': 'User Accounts',
    'admin.currentPassword': 'Current password',
    'admin.newPassword': 'New password',
    'admin.confirmNewPassword': 'Confirm new password',
    'admin.changePassword': 'Change Password',
    'admin.passwordChanged': 'Password changed successfully',
    'admin.userPasswordChanged': 'User password changed successfully',
    'admin.passwordError': 'Error changing password',
    'admin.noUsers': 'No registered users',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure SMS and Email APIs',
    'settings.backToAdmin': 'Back to Dashboard',
    'settings.vonageTitle': 'Vonage SMS Configuration',
    'settings.vonageSubtitle': 'Configure Vonage API credentials to send SMS to clients.',
    'settings.smtpTitle': 'Email SMTP Configuration',
    'settings.smtpSubtitle': 'Configure SMTP server to send confirmation emails.',
    'settings.smtpHost': 'SMTP Server',
    'settings.smtpPort': 'Port',
    'settings.smtpUser': 'SMTP Username',
    'settings.smtpPass': 'Password',
    'settings.smtpPassHint': 'For Gmail, use an app-specific password',
    'settings.fromNumber': 'Sender Name/Number',
    'settings.fromEmail': 'Sender Email',
    'settings.configured': 'Configured',
    'settings.notConfigured': 'Not configured',
    'settings.save': 'Save',
    'settings.test': 'Test',
    'settings.vonageSaved': 'Vonage configuration saved',
    'settings.smtpSaved': 'SMTP configuration saved',
    'settings.saveError': 'Error saving',
    'settings.vonageTestSuccess': 'Vonage connection successful',
    'settings.vonageTestError': 'Error connecting to Vonage',
    'settings.smtpTestSuccess': 'SMTP connection successful',
    'settings.smtpTestError': 'Error connecting to SMTP',
    'settings.testSms': 'Send Test SMS',
    'settings.testPhone': 'Phone Number',
    'settings.testPhoneHint': 'Include country code (+48...)',
    'settings.sendTestSms': 'Send SMS',
    'settings.enterTestPhone': 'Enter a phone number',
    'settings.smsTestSuccess': 'SMS sent successfully',
    'settings.smsTestError': 'Error sending SMS',
    'settings.keepExisting': 'Leave empty to keep current value',
    'settings.testEmail': 'Send Test Email',
    'settings.testEmailAddress': 'Email address',
    'settings.sendTestEmail': 'Send Email',
    'settings.enterTestEmail': 'Enter an email address',
    'settings.emailTestSuccess': 'Email sent successfully',
    'settings.emailTestError': 'Error sending email',
  },
  cs: {
    // Navigation
    'nav.services': 'Služby',
    'nav.about': 'O nás',
    'nav.contact': 'Kontakt',
    'nav.privacy': 'Soukromí',
    'nav.start': 'Začít',

    // Hero
    'hero.badge': 'Zemědělství budoucnosti',
    'hero.title1': 'Transformujte své',
    'hero.title2': 'zemědělství s drony',
    'hero.description': 'Služby přesného zemědělství s nejmodernější technologií. Maximalizujte výnosy svých plodin pomocí chytrých řešení.',
    'hero.cta': 'Objednat službu',
    'hero.viewServices': 'Zobrazit služby',

    // Stats
    'stats.hectares': 'Ošetřených hektarů',
    'stats.precision': 'Přesnost',
    'stats.response': 'Odezva',
    'stats.clients': 'Klientů',

    // Services
    'services.title': 'Naše služby',
    'services.subtitle': 'Zemědělská',
    'services.subtitleHighlight': 'řešení',
    'service.fumigation.title': 'Postřik dronem',
    'service.fumigation.desc': 'Přesná aplikace fytosanitárních přípravků s nejmodernější technologií.',
    'service.painting.title': 'Nátěr skleníků',
    'service.painting.desc': 'UV ochrana a regulace klimatu pro optimalizaci růstu vašich plodin.',
    'service.mapping.title': 'Letecké mapování',
    'service.mapping.desc': 'Detailní analýza terénu s obrazy ve vysokém rozlišení a přesnými daty.',
    'service.elevation.title': 'Výškové modely',
    'service.elevation.desc': 'Plánování zavlažování a odvodnění s vysoce přesnými 3D topografickými modely.',
    'service.rental.title': 'Pronájem dronů',
    'service.rental.desc': 'Pronájem profesionálních zemědělských dronů s operátorem nebo bez pro vaše projekty.',

    // About
    'about.title': 'O nás',
    'about.subtitle': 'Inovace ve službách',
    'about.subtitleHighlight': 'zemědělství',
    'about.description': 'Jsme průkopníky v aplikaci dronové technologie v zemědělství. Náš tým odborníků kombinuje zemědělské znalosti s nejmodernější technologií.',
    'about.feature1': 'Nejmodernější technologie',
    'about.feature2': 'Certifikovaný tým odborníků',
    'about.feature3': 'Závazek k životnímu prostředí',
    'about.feature4': 'Garantované výsledky',
    'about.years': 'Let zkušeností',
    'about.drones': 'Dronů ve flotile',
    'about.support': 'Technická podpora',
    'about.satisfaction': 'Spokojenost',

    // CTA
    'cta.title': 'Připraveni',
    'cta.titleHighlight': 'transformovat',
    'cta.titleEnd': 'své zemědělství?',
    'cta.description': 'Připojte se ke stovkám farmářů, kteří již využívají sílu dronů.',
    'cta.button': 'Začít nyní',

    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Pojďme si promluvit o vašem',
    'contact.subtitleHighlight': 'projektu',
    'contact.description': 'Jsme tu, abychom vám pomohli. Kontaktujte nás a odpovíme do 24 hodin.',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.address': 'Adresa',
    'contact.form.name': 'Jméno',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Předmět',
    'contact.form.message': 'Zpráva',
    'contact.form.send': 'Odeslat zprávu',
    'contact.viewLargerMap': 'Zobrazit větší mapu',

    // Footer
    'footer.rights': 'Všechna práva vyhrazena.',
    'footer.privacy': 'Zásady ochrany osobních údajů',

    // Privacy
    'privacy.title': 'Zásady ochrany osobních údajů',
    'privacy.back': 'Zpět na hlavní stránku',
    'privacy.lastUpdated': 'Poslední aktualizace',
    'privacy.intro': 'V Drone Service se zavazujeme chránit vaše soukromí a osobní údaje.',
    'privacy.gdprCompliant': 'V souladu s GDPR',
    'privacy.gdprDescription': 'Tyto zásady jsou v souladu s obecným nařízením o ochraně osobních údajů (EU) 2016/679',
    'privacy.section1.title': 'Správce údajů',
    'privacy.section1.content': 'Drone Service se sídlem Ul. Smolna 14, 44-200 Rybnik, Polsko, je správcem vašich osobních údajů.',
    'privacy.section2.title': 'Údaje, které shromažďujeme',
    'privacy.section2.content': 'Shromažďujeme následující typy osobních údajů:\n\n- Identifikační údaje: jméno, příjmení, email, telefon\n- Údaje o poloze: adresa farmy nebo pozemku\n- Údaje o službách: typ požadované služby, data, pracovní plocha',
    'privacy.section3.title': 'Účel zpracování',
    'privacy.section3.content': 'Vaše osobní údaje používáme k:\n\n- Správě a zpracování vašich požadavků na služby\n- Komunikaci s vámi o stavu vašich služeb\n- Zasílání potvrzení a oznámení',
    'privacy.section4.title': 'Právní základ zpracování',
    'privacy.section4.content': 'Zpracování vašich údajů je založeno na vašem výslovném souhlasu.',
    'privacy.section5.title': 'Vaše práva',
    'privacy.section5.content': 'Podle GDPR máte právo na přístup, opravu, výmaz a přenositelnost vašich údajů.',
    'privacy.section6.title': 'Uchovávání údajů',
    'privacy.section6.content': 'Vaše osobní údaje uchováváme po dobu nezbytnou k naplnění účelů.',
    'privacy.section7.title': 'Zabezpečení údajů',
    'privacy.section7.content': 'Implementujeme vhodná technická a organizační opatření k ochraně vašich osobních údajů.',
    'privacy.section8.title': 'Kontakt a stížnosti',
    'privacy.section8.content': 'Pro uplatnění vašich práv nás kontaktujte na admin@drone-partss.com.',
    'privacy.contact.title': 'Kontakt pro ochranu soukromí',
    'privacy.contact.description': 'Máte-li dotazy k těmto zásadám:',

    // Auth
    'auth.login': 'Přihlásit se',
    'auth.signup': 'Registrovat se',
    'auth.back': 'Zpět',
    'auth.name': 'Celé jméno',
    'auth.phone': 'Telefon',
    'auth.email': 'Email',
    'auth.password': 'Heslo',
    'auth.confirmPassword': 'Potvrdit heslo',
    'auth.forgotPassword': 'Zapomněli jste heslo?',
    'auth.loginButton': 'Přihlásit se',
    'auth.signupButton': 'Vytvořit účet',
    'auth.loggingIn': 'Přihlašování...',
    'auth.signingUp': 'Registrace...',
    'auth.continueWith': 'nebo pokračujte s',
    'auth.terms': 'Registrací souhlasíte s našimi',
    'auth.termsLink': 'Podmínkami služby',
    'auth.and': 'a',
    'auth.privacyLink': 'Zásadami ochrany soukromí',
    'auth.passwordMismatch': 'Hesla se neshodují',

    // Forgot Password
    'forgotPassword.title': 'Obnovit Heslo',
    'forgotPassword.description': 'Zadejte svůj email a pošleme vám instrukce k obnovení hesla.',
    'forgotPassword.sendButton': 'Odeslat Instrukce',
    'forgotPassword.sending': 'Odesílání...',
    'forgotPassword.success': 'Pokud email existuje, obdržíte instrukce k obnovení hesla.',
    'forgotPassword.error': 'Chyba při zpracování požadavku',
    'forgotPassword.close': 'Zavřít',

    // Reset Password
    'resetPassword.title': 'Nové Heslo',
    'resetPassword.newPassword': 'Nové heslo',
    'resetPassword.confirmPassword': 'Potvrdit heslo',
    'resetPassword.resetButton': 'Obnovit Heslo',
    'resetPassword.resetting': 'Obnovování...',
    'resetPassword.success': 'Vaše heslo bylo úspěšně obnoveno.',
    'resetPassword.goToLogin': 'Přejít na Přihlášení',
    'resetPassword.error': 'Chyba při obnovování hesla',
    'resetPassword.minLength': 'Heslo musí mít alespoň 6 znaků',

    // Dashboard
    'dashboard.title': 'Panel klienta',
    'dashboard.welcome': 'Vítejte',
    'dashboard.logout': 'Odhlásit se',
    'dashboard.calendar': 'Kalendář',
    'dashboard.jobs': 'Práce',
    'dashboard.completed': 'Dokončené',
    'dashboard.scheduled': 'Naplánované',
    'dashboard.confirmed': 'Potvrzené',
    'dashboard.inProgress': 'Probíhá',
    'dashboard.pending': 'Čekající',
    'dashboard.all': 'Všechny',
    'dashboard.noJobs': 'Žádné registrované práce',
    'dashboard.requestService': 'Objednat službu',
    'dashboard.status.completed': 'Dokončeno',
    'dashboard.status.scheduled': 'Naplánováno',
    'dashboard.status.confirmed': 'Potvrzeno',
    'dashboard.status.in_progress': 'Probíhá',
    'dashboard.status.cancelled': 'Zrušeno',
    'dashboard.status.pending': 'Čeká',
    'dashboard.status.inProgress': 'Probíhá',
    'dashboard.jobDetails': 'Detaily práce',
    'dashboard.date': 'Datum',
    'dashboard.service': 'Služba',
    'dashboard.location': 'Lokace',
    'dashboard.area': 'Plocha',
    'dashboard.hectares': 'hektarů',
    'dashboard.today': 'Dnes',
    'dashboard.thisMonth': 'Tento měsíc',
    'dashboard.upcoming': 'Nadcházející',
    'dashboard.past': 'Minulé',

    // Service Request Modal
    'serviceRequest.title': 'Objednat službu',
    'serviceRequest.step': 'Krok',
    'serviceRequest.of': 'z',
    'serviceRequest.selectService': 'Jakou službu potřebujete?',
    'serviceRequest.selectDate': 'Vyberte datum',
    'serviceRequest.selectTime': 'Vyberte čas',
    'serviceRequest.form.name': 'Jméno',
    'serviceRequest.form.email': 'Email',
    'serviceRequest.form.phone': 'Telefon',
    'serviceRequest.form.location': 'Lokace pozemku',
    'serviceRequest.form.locationPlaceholder': 'Adresa nebo souřadnice',
    'serviceRequest.form.area': 'Plocha (hektary)',
    'serviceRequest.form.areaPlaceholder': 'Např.: 5',
    'serviceRequest.form.notes': 'Další poznámky',
    'serviceRequest.form.notesPlaceholder': 'Další informace o službě...',
    'serviceRequest.summary': 'Souhrn objednávky',
    'serviceRequest.summaryService': 'Služba',
    'serviceRequest.summaryDate': 'Datum',
    'serviceRequest.summaryTime': 'Čas',
    'serviceRequest.back': 'Zpět',
    'serviceRequest.next': 'Další',
    'serviceRequest.submit': 'Odeslat objednávku',
    'serviceRequest.success.title': 'Objednávka odeslána!',
    'serviceRequest.success.message': 'Obdrželi jsme vaši objednávku. Budeme vás kontaktovat do 24 hodin.',
    'serviceRequest.success.close': 'Zavřít',
    'serviceRequest.floatingButton': 'Objednat službu',
    'serviceRequest.sending': 'Odesílání...',
    'serviceRequest.rental.dateRange': 'Období pronájmu',
    'serviceRequest.rental.startDate': 'Datum zahájení',
    'serviceRequest.rental.endDate': 'Datum ukončení',
    'serviceRequest.rental.totalDays': 'Celkem dní',
    'serviceRequest.rental.day': 'den',
    'serviceRequest.rental.days': 'dní',
    'serviceRequest.rental.pickupTime': 'Čas vyzvednutí',

    // Weather Forecast
    'weather.loading': 'Načítání předpovědi...',
    'weather.errorLoading': 'Nepodařilo se načíst předpověď',
    'weather.noForecast': 'Předpověď není pro toto datum k dispozici',
    'weather.forecast': 'Předpověď počasí',
    'weather.rentalForecast': 'Předpověď na období',
    'weather.temperature': 'Teplota',
    'weather.precipitation': 'Šance deště',
    'weather.wind': 'Vítr',
    'weather.uvIndex': 'UV index',
    'weather.avgTemp': 'Prům. teplota',
    'weather.maxPrecipProb': 'Max. šance deště',
    'weather.totalPrecip': 'Celk. srážky',
    'weather.droneGood': 'Optimální podmínky pro let dronu',
    'weather.droneModerate': 'Přijatelné podmínky, zkontrolujte před letem',
    'weather.dronePoor': 'Nepříznivé podmínky pro let dronu',
    'weather.droneGoodRange': 'Na období se očekává dobré počasí',
    'weather.droneModerateRange': 'Některé dny s proměnlivými podmínkami',
    'weather.dronePoorRange': 'Očekávají se dny se špatným počasím',
    'weather.sunny': 'Slunečno',
    'weather.lightClouds': 'Lehká oblačnost',
    'weather.partlyCloudy': 'Polojasno',
    'weather.cloudy': 'Oblačno',
    'weather.rain': 'Déšť',
    'weather.rainSnow': 'Déšť se sněhem',
    'weather.snow': 'Sníh',
    'weather.rainSnowShowers': 'Sněhové přeháňky',
    'weather.foggy': 'Mlha',
    'weather.lightRain': 'Lehký déšť',
    'weather.heavyRain': 'Silný déšť',
    'weather.lightSnow': 'Lehké sněžení',
    'weather.heavySnow': 'Silné sněžení',
    'weather.rainShowers': 'Přeháňky',
    'weather.snowShowers': 'Sněhové přeháňky',
    'weather.thunderstorm': 'Bouřka',
    'weather.hail': 'Kroupy',
    'weather.unknown': 'Neznámé',

    // Admin
    'admin.title': 'Administrační panel',
    'admin.subtitle': 'Spravujte všechny požadavky na služby',
    'admin.requests': 'Požadavky na služby',
    'admin.noRequests': 'Žádné požadavky',
    'admin.confirm': 'Potvrdit',
    'admin.complete': 'Dokončit',
    'admin.startWork': 'Zahájit práci',
    'admin.cancel': 'Zrušit',
    'admin.delete': 'Smazat',
    'admin.confirmDelete': 'Potvrdit',
    'admin.refresh': 'Obnovit',
    'admin.statusError': 'Chyba při aktualizaci stavu',
    'admin.deleteError': 'Chyba při mazání požadavku',
    'admin.viewDetails': 'Zobrazit detaily',
    'admin.smsSent': 'SMS odesláno klientovi',
    'admin.smsError': 'Chyba při odesílání SMS',
    'admin.sendingSms': 'Odesílání SMS...',
    'admin.notificationsSent': 'SMS a Email odeslány',
    'admin.notificationsError': 'Chyba při odesílání oznámení',

    // Password Management
    'admin.passwordManagement': 'Správa Hesel',
    'admin.changeOwnPassword': 'Změnit Moje Heslo',
    'admin.userAccounts': 'Uživatelské Účty',
    'admin.currentPassword': 'Aktuální heslo',
    'admin.newPassword': 'Nové heslo',
    'admin.confirmNewPassword': 'Potvrdit nové heslo',
    'admin.changePassword': 'Změnit Heslo',
    'admin.passwordChanged': 'Heslo bylo úspěšně změněno',
    'admin.userPasswordChanged': 'Heslo uživatele bylo změněno',
    'admin.passwordError': 'Chyba při změně hesla',
    'admin.noUsers': 'Žádní registrovaní uživatelé',

    // Settings
    'settings.title': 'Nastavení',
    'settings.subtitle': 'Konfigurace SMS a Email API',
    'settings.backToAdmin': 'Zpět na panel',
    'settings.vonageTitle': 'Konfigurace Vonage SMS',
    'settings.vonageSubtitle': 'Nakonfigurujte přihlašovací údaje Vonage API.',
    'settings.smtpTitle': 'Konfigurace Email SMTP',
    'settings.smtpSubtitle': 'Nakonfigurujte SMTP server pro odesílání emailů.',
    'settings.smtpHost': 'SMTP Server',
    'settings.smtpPort': 'Port',
    'settings.smtpUser': 'SMTP uživatel',
    'settings.smtpPass': 'Heslo',
    'settings.smtpPassHint': 'Pro Gmail použijte heslo aplikace',
    'settings.fromNumber': 'Jméno/Číslo odesílatele',
    'settings.fromEmail': 'Email odesílatele',
    'settings.configured': 'Nakonfigurováno',
    'settings.notConfigured': 'Nenakonfigurováno',
    'settings.save': 'Uložit',
    'settings.test': 'Test',
    'settings.vonageSaved': 'Konfigurace Vonage uložena',
    'settings.smtpSaved': 'Konfigurace SMTP uložena',
    'settings.saveError': 'Chyba při ukládání',
    'settings.vonageTestSuccess': 'Připojení k Vonage úspěšné',
    'settings.vonageTestError': 'Chyba připojení k Vonage',
    'settings.smtpTestSuccess': 'Připojení SMTP úspěšné',
    'settings.smtpTestError': 'Chyba připojení SMTP',
    'settings.testSms': 'Odeslat testovací SMS',
    'settings.testPhone': 'Telefonní číslo',
    'settings.testPhoneHint': 'Včetně kódu země (+48...)',
    'settings.sendTestSms': 'Odeslat SMS',
    'settings.enterTestPhone': 'Zadejte telefonní číslo',
    'settings.smsTestSuccess': 'SMS úspěšně odeslána',
    'settings.smsTestError': 'Chyba při odesílání SMS',
    'settings.keepExisting': 'Nechte prázdné pro zachování aktuální hodnoty',
    'settings.testEmail': 'Odeslat testovací Email',
    'settings.testEmailAddress': 'Emailová adresa',
    'settings.sendTestEmail': 'Odeslat Email',
    'settings.enterTestEmail': 'Zadejte emailovou adresu',
    'settings.emailTestSuccess': 'Email úspěšně odeslán',
    'settings.emailTestError': 'Chyba při odesílání emailu',
  },
  sk: {
    // Navigation
    'nav.services': 'Služby',
    'nav.about': 'O nás',
    'nav.contact': 'Kontakt',
    'nav.privacy': 'Súkromie',
    'nav.start': 'Začať',

    // Hero
    'hero.badge': 'Poľnohospodárstvo budúcnosti',
    'hero.title1': 'Transformujte svoje',
    'hero.title2': 'poľnohospodárstvo s dronmi',
    'hero.description': 'Služby presného poľnohospodárstva s najmodernejšou technológiou. Maximalizujte výnosy svojich plodín pomocou inteligentných riešení.',
    'hero.cta': 'Objednať službu',
    'hero.viewServices': 'Zobraziť služby',

    // Stats
    'stats.hectares': 'Ošetrených hektárov',
    'stats.precision': 'Presnosť',
    'stats.response': 'Odozva',
    'stats.clients': 'Klientov',

    // Services
    'services.title': 'Naše služby',
    'services.subtitle': 'Poľnohospodárske',
    'services.subtitleHighlight': 'riešenia',
    'service.fumigation.title': 'Postrekovanie dronom',
    'service.fumigation.desc': 'Presná aplikácia fytosanitárnych prípravkov s najmodernejšou technológiou.',
    'service.painting.title': 'Náter skleníkov',
    'service.painting.desc': 'UV ochrana a regulácia klímy pre optimalizáciu rastu vašich plodín.',
    'service.mapping.title': 'Letecké mapovanie',
    'service.mapping.desc': 'Detailná analýza terénu s obrázkami vo vysokom rozlíšení a presnými údajmi.',
    'service.elevation.title': 'Výškové modely',
    'service.elevation.desc': 'Plánovanie zavlažovania a odvodnenia s vysoko presnými 3D topografickými modelmi.',
    'service.rental.title': 'Prenájom dronov',
    'service.rental.desc': 'Prenájom profesionálnych poľnohospodárskych dronov s operátorom alebo bez pre vaše projekty.',

    // About
    'about.title': 'O nás',
    'about.subtitle': 'Inovácie v službách',
    'about.subtitleHighlight': 'poľnohospodárstva',
    'about.description': 'Sme priekopníkmi v aplikácii dronovej technológie v poľnohospodárstve. Náš tím odborníkov kombinuje poľnohospodárske znalosti s najmodernejšou technológiou.',
    'about.feature1': 'Najmodernejšia technológia',
    'about.feature2': 'Certifikovaný tím odborníkov',
    'about.feature3': 'Záväzok k životnému prostrediu',
    'about.feature4': 'Garantované výsledky',
    'about.years': 'Rokov skúseností',
    'about.drones': 'Dronov vo flotile',
    'about.support': 'Technická podpora',
    'about.satisfaction': 'Spokojnosť',

    // CTA
    'cta.title': 'Pripravení',
    'cta.titleHighlight': 'transformovať',
    'cta.titleEnd': 'svoje poľnohospodárstvo?',
    'cta.description': 'Pripojte sa k stovkám farmárov, ktorí už využívajú silu dronov.',
    'cta.button': 'Začať teraz',

    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Porozprávajme sa o vašom',
    'contact.subtitleHighlight': 'projekte',
    'contact.description': 'Sme tu, aby sme vám pomohli. Kontaktujte nás a odpovieme do 24 hodín.',
    'contact.phone': 'Telefón',
    'contact.email': 'Email',
    'contact.address': 'Adresa',
    'contact.form.name': 'Meno',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Predmet',
    'contact.form.message': 'Správa',
    'contact.form.send': 'Odoslať správu',
    'contact.viewLargerMap': 'Zobraziť väčšiu mapu',

    // Footer
    'footer.rights': 'Všetky práva vyhradené.',
    'footer.privacy': 'Zásady ochrany osobných údajov',

    // Privacy
    'privacy.title': 'Zásady ochrany osobných údajov',
    'privacy.back': 'Späť na hlavnú stránku',
    'privacy.lastUpdated': 'Posledná aktualizácia',
    'privacy.intro': 'V Drone Service sa zaväzujeme chrániť vaše súkromie a osobné údaje.',
    'privacy.gdprCompliant': 'V súlade s GDPR',
    'privacy.gdprDescription': 'Tieto zásady sú v súlade so všeobecným nariadením o ochrane osobných údajov (EÚ) 2016/679',
    'privacy.section1.title': 'Správca údajov',
    'privacy.section1.content': 'Drone Service so sídlom Ul. Smolna 14, 44-200 Rybnik, Poľsko, je správcom vašich osobných údajov.',
    'privacy.section2.title': 'Údaje, ktoré zhromažďujeme',
    'privacy.section2.content': 'Zhromažďujeme nasledujúce typy osobných údajov:\n\n- Identifikačné údaje: meno, priezvisko, email, telefón\n- Údaje o polohe: adresa farmy alebo pozemku\n- Údaje o službách: typ požadovanej služby, dáta, pracovná plocha',
    'privacy.section3.title': 'Účel spracovania',
    'privacy.section3.content': 'Vaše osobné údaje používame na:\n\n- Správu a spracovanie vašich požiadaviek na služby\n- Komunikáciu s vami o stave vašich služieb\n- Zasielanie potvrdení a oznámení',
    'privacy.section4.title': 'Právny základ spracovania',
    'privacy.section4.content': 'Spracovanie vašich údajov je založené na vašom výslovnom súhlase.',
    'privacy.section5.title': 'Vaše práva',
    'privacy.section5.content': 'Podľa GDPR máte právo na prístup, opravu, vymazanie a prenosnosť vašich údajov.',
    'privacy.section6.title': 'Uchovávanie údajov',
    'privacy.section6.content': 'Vaše osobné údaje uchovávame po dobu nevyhnutnú na naplnenie účelov.',
    'privacy.section7.title': 'Zabezpečenie údajov',
    'privacy.section7.content': 'Implementujeme vhodné technické a organizačné opatrenia na ochranu vašich osobných údajov.',
    'privacy.section8.title': 'Kontakt a sťažnosti',
    'privacy.section8.content': 'Pre uplatnenie vašich práv nás kontaktujte na admin@drone-partss.com.',
    'privacy.contact.title': 'Kontakt pre ochranu súkromia',
    'privacy.contact.description': 'Máte otázky k týmto zásadám:',

    // Auth
    'auth.login': 'Prihlásiť sa',
    'auth.signup': 'Registrovať sa',
    'auth.back': 'Späť',
    'auth.name': 'Celé meno',
    'auth.phone': 'Telefón',
    'auth.email': 'Email',
    'auth.password': 'Heslo',
    'auth.confirmPassword': 'Potvrdiť heslo',
    'auth.forgotPassword': 'Zabudli ste heslo?',
    'auth.loginButton': 'Prihlásiť sa',
    'auth.signupButton': 'Vytvoriť účet',
    'auth.loggingIn': 'Prihlasovanie...',
    'auth.signingUp': 'Registrácia...',
    'auth.continueWith': 'alebo pokračujte s',
    'auth.terms': 'Registráciou súhlasíte s našimi',
    'auth.termsLink': 'Podmienkami služby',
    'auth.and': 'a',
    'auth.privacyLink': 'Zásadami ochrany súkromia',
    'auth.passwordMismatch': 'Heslá sa nezhodujú',

    // Forgot Password
    'forgotPassword.title': 'Obnoviť Heslo',
    'forgotPassword.description': 'Zadajte svoj email a pošleme vám inštrukcie na obnovenie hesla.',
    'forgotPassword.sendButton': 'Odoslať Inštrukcie',
    'forgotPassword.sending': 'Odosielanie...',
    'forgotPassword.success': 'Ak email existuje, dostanete inštrukcie na obnovenie hesla.',
    'forgotPassword.error': 'Chyba pri spracovaní požiadavky',
    'forgotPassword.close': 'Zavrieť',

    // Reset Password
    'resetPassword.title': 'Nové Heslo',
    'resetPassword.newPassword': 'Nové heslo',
    'resetPassword.confirmPassword': 'Potvrdiť heslo',
    'resetPassword.resetButton': 'Obnoviť Heslo',
    'resetPassword.resetting': 'Obnovuje sa...',
    'resetPassword.success': 'Vaše heslo bolo úspešne obnovené.',
    'resetPassword.goToLogin': 'Prejsť na Prihlásenie',
    'resetPassword.error': 'Chyba pri obnovovaní hesla',
    'resetPassword.minLength': 'Heslo musí mať aspoň 6 znakov',

    // Dashboard
    'dashboard.title': 'Panel klienta',
    'dashboard.welcome': 'Vitajte',
    'dashboard.logout': 'Odhlásiť sa',
    'dashboard.calendar': 'Kalendár',
    'dashboard.jobs': 'Práce',
    'dashboard.completed': 'Dokončené',
    'dashboard.scheduled': 'Naplánované',
    'dashboard.confirmed': 'Potvrdené',
    'dashboard.inProgress': 'Prebieha',
    'dashboard.pending': 'Čakajúce',
    'dashboard.all': 'Všetky',
    'dashboard.noJobs': 'Žiadne registrované práce',
    'dashboard.requestService': 'Objednať službu',
    'dashboard.status.completed': 'Dokončené',
    'dashboard.status.scheduled': 'Naplánované',
    'dashboard.status.confirmed': 'Potvrdené',
    'dashboard.status.in_progress': 'Prebieha',
    'dashboard.status.cancelled': 'Zrušené',
    'dashboard.status.pending': 'Čaká',
    'dashboard.status.inProgress': 'Prebieha',
    'dashboard.jobDetails': 'Detaily práce',
    'dashboard.date': 'Dátum',
    'dashboard.service': 'Služba',
    'dashboard.location': 'Lokácia',
    'dashboard.area': 'Plocha',
    'dashboard.hectares': 'hektárov',
    'dashboard.today': 'Dnes',
    'dashboard.thisMonth': 'Tento mesiac',
    'dashboard.upcoming': 'Nadchádzajúce',
    'dashboard.past': 'Minulé',

    // Service Request Modal
    'serviceRequest.title': 'Objednať službu',
    'serviceRequest.step': 'Krok',
    'serviceRequest.of': 'z',
    'serviceRequest.selectService': 'Akú službu potrebujete?',
    'serviceRequest.selectDate': 'Vyberte dátum',
    'serviceRequest.selectTime': 'Vyberte čas',
    'serviceRequest.form.name': 'Meno',
    'serviceRequest.form.email': 'Email',
    'serviceRequest.form.phone': 'Telefón',
    'serviceRequest.form.location': 'Lokácia pozemku',
    'serviceRequest.form.locationPlaceholder': 'Adresa alebo súradnice',
    'serviceRequest.form.area': 'Plocha (hektáre)',
    'serviceRequest.form.areaPlaceholder': 'Napr.: 5',
    'serviceRequest.form.notes': 'Ďalšie poznámky',
    'serviceRequest.form.notesPlaceholder': 'Ďalšie informácie o službe...',
    'serviceRequest.summary': 'Súhrn objednávky',
    'serviceRequest.summaryService': 'Služba',
    'serviceRequest.summaryDate': 'Dátum',
    'serviceRequest.summaryTime': 'Čas',
    'serviceRequest.back': 'Späť',
    'serviceRequest.next': 'Ďalej',
    'serviceRequest.submit': 'Odoslať objednávku',
    'serviceRequest.success.title': 'Objednávka odoslaná!',
    'serviceRequest.success.message': 'Dostali sme vašu objednávku. Budeme vás kontaktovať do 24 hodín.',
    'serviceRequest.success.close': 'Zavrieť',
    'serviceRequest.floatingButton': 'Objednať službu',
    'serviceRequest.sending': 'Odosielanie...',
    'serviceRequest.rental.dateRange': 'Obdobie prenájmu',
    'serviceRequest.rental.startDate': 'Dátum začiatku',
    'serviceRequest.rental.endDate': 'Dátum ukončenia',
    'serviceRequest.rental.totalDays': 'Celkom dní',
    'serviceRequest.rental.day': 'deň',
    'serviceRequest.rental.days': 'dní',
    'serviceRequest.rental.pickupTime': 'Čas vyzdvihnutia',

    // Weather Forecast
    'weather.loading': 'Načítava sa predpoveď...',
    'weather.errorLoading': 'Nepodarilo sa načítať predpoveď',
    'weather.noForecast': 'Predpoveď nie je pre tento dátum k dispozícii',
    'weather.forecast': 'Predpoveď počasia',
    'weather.rentalForecast': 'Predpoveď na obdobie',
    'weather.temperature': 'Teplota',
    'weather.precipitation': 'Šanca dažďa',
    'weather.wind': 'Vietor',
    'weather.uvIndex': 'UV index',
    'weather.avgTemp': 'Priem. teplota',
    'weather.maxPrecipProb': 'Max. šanca dažďa',
    'weather.totalPrecip': 'Celk. zrážky',
    'weather.droneGood': 'Optimálne podmienky pre let dronu',
    'weather.droneModerate': 'Prijateľné podmienky, skontrolujte pred letom',
    'weather.dronePoor': 'Nepriaznivé podmienky pre let dronu',
    'weather.droneGoodRange': 'Na obdobie sa očakáva dobré počasie',
    'weather.droneModerateRange': 'Niektoré dni s premenlivými podmienkami',
    'weather.dronePoorRange': 'Očakávajú sa dni so zlým počasím',
    'weather.sunny': 'Slnečno',
    'weather.lightClouds': 'Ľahká oblačnosť',
    'weather.partlyCloudy': 'Polojasno',
    'weather.cloudy': 'Oblačno',
    'weather.rain': 'Dážď',
    'weather.rainSnow': 'Dážď so snehom',
    'weather.snow': 'Sneh',
    'weather.rainSnowShowers': 'Snehové prehánky',
    'weather.foggy': 'Hmla',
    'weather.lightRain': 'Ľahký dážď',
    'weather.heavyRain': 'Silný dážď',
    'weather.lightSnow': 'Ľahké sneženie',
    'weather.heavySnow': 'Silné sneženie',
    'weather.rainShowers': 'Prehánky',
    'weather.snowShowers': 'Snehové prehánky',
    'weather.thunderstorm': 'Búrka',
    'weather.hail': 'Krupobitie',
    'weather.unknown': 'Neznáme',

    // Admin
    'admin.title': 'Administračný panel',
    'admin.subtitle': 'Spravujte všetky požiadavky na služby',
    'admin.requests': 'Požiadavky na služby',
    'admin.noRequests': 'Žiadne požiadavky',
    'admin.confirm': 'Potvrdiť',
    'admin.complete': 'Dokončiť',
    'admin.startWork': 'Začať prácu',
    'admin.cancel': 'Zrušiť',
    'admin.delete': 'Vymazať',
    'admin.confirmDelete': 'Potvrdiť',
    'admin.refresh': 'Obnoviť',
    'admin.statusError': 'Chyba pri aktualizácii stavu',
    'admin.deleteError': 'Chyba pri mazaní požiadavky',
    'admin.viewDetails': 'Zobraziť detaily',
    'admin.smsSent': 'SMS odoslaný klientovi',
    'admin.smsError': 'Chyba pri odosielaní SMS',
    'admin.sendingSms': 'Odosielanie SMS...',
    'admin.notificationsSent': 'SMS a Email odoslané',
    'admin.notificationsError': 'Chyba pri odosielaní oznámení',

    // Password Management
    'admin.passwordManagement': 'Správa Hesiel',
    'admin.changeOwnPassword': 'Zmeniť Moje Heslo',
    'admin.userAccounts': 'Používateľské Účty',
    'admin.currentPassword': 'Aktuálne heslo',
    'admin.newPassword': 'Nové heslo',
    'admin.confirmNewPassword': 'Potvrdiť nové heslo',
    'admin.changePassword': 'Zmeniť Heslo',
    'admin.passwordChanged': 'Heslo bolo úspešne zmenené',
    'admin.userPasswordChanged': 'Heslo používateľa bolo zmenené',
    'admin.passwordError': 'Chyba pri zmene hesla',
    'admin.noUsers': 'Žiadni registrovaní používatelia',

    // Settings
    'settings.title': 'Nastavenia',
    'settings.subtitle': 'Konfigurácia SMS a Email API',
    'settings.backToAdmin': 'Späť na panel',
    'settings.vonageTitle': 'Konfigurácia Vonage SMS',
    'settings.vonageSubtitle': 'Nakonfigurujte prihlasovacie údaje Vonage API.',
    'settings.smtpTitle': 'Konfigurácia Email SMTP',
    'settings.smtpSubtitle': 'Nakonfigurujte SMTP server pre odosielanie emailov.',
    'settings.smtpHost': 'SMTP Server',
    'settings.smtpPort': 'Port',
    'settings.smtpUser': 'SMTP používateľ',
    'settings.smtpPass': 'Heslo',
    'settings.smtpPassHint': 'Pre Gmail použite heslo aplikácie',
    'settings.fromNumber': 'Meno/Číslo odosielateľa',
    'settings.fromEmail': 'Email odosielateľa',
    'settings.configured': 'Nakonfigurované',
    'settings.notConfigured': 'Nenakonfigurované',
    'settings.save': 'Uložiť',
    'settings.test': 'Test',
    'settings.vonageSaved': 'Konfigurácia Vonage uložená',
    'settings.smtpSaved': 'Konfigurácia SMTP uložená',
    'settings.saveError': 'Chyba pri ukladaní',
    'settings.vonageTestSuccess': 'Pripojenie k Vonage úspešné',
    'settings.vonageTestError': 'Chyba pripojenia k Vonage',
    'settings.smtpTestSuccess': 'Pripojenie SMTP úspešné',
    'settings.smtpTestError': 'Chyba pripojenia SMTP',
    'settings.testSms': 'Odoslať testovací SMS',
    'settings.testPhone': 'Telefónne číslo',
    'settings.testPhoneHint': 'Vrátane kódu krajiny (+48...)',
    'settings.sendTestSms': 'Odoslať SMS',
    'settings.enterTestPhone': 'Zadajte telefónne číslo',
    'settings.smsTestSuccess': 'SMS úspešne odoslaná',
    'settings.smsTestError': 'Chyba pri odosielaní SMS',
    'settings.keepExisting': 'Nechajte prázdne pre zachovanie aktuálnej hodnoty',
    'settings.testEmail': 'Odoslať testovací Email',
    'settings.testEmailAddress': 'Emailová adresa',
    'settings.sendTestEmail': 'Odoslať Email',
    'settings.enterTestEmail': 'Zadajte emailovú adresu',
    'settings.emailTestSuccess': 'Email úspešne odoslaný',
    'settings.emailTestError': 'Chyba pri odosielaní emailu',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language
      return saved || 'es'
    }
    return 'es'
  })

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
